# badge: https://github.com/borgbackup/borgstore/workflows/CI/badge.svg?branch=master

name: CI

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
    - '**.yml'
    - '**.toml'
    - '**.cfg'
    - '**.ini'
    - 'requirements.d/*'
    - '!docs/**'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'
    - '**.yml'
    - '**.toml'
    - '**.cfg'
    - '**.ini'
    - 'requirements.d/*'
    - '!docs/**'

jobs:
  linux:

    strategy:
      fail-fast: true
      matrix:
        include:
            - os: ubuntu-24.04
              python-version: '3.11'
              toxenv: flake8
            - os: ubuntu-24.04
              python-version: '3.11'
              toxenv: mypy
            - os: ubuntu-22.04
              python-version: '3.9'
              toxenv: py39
            - os: ubuntu-22.04
              python-version: '3.10'
              toxenv: py310
            - os: ubuntu-24.04
              python-version: '3.11'
              toxenv: py311
            - os: ubuntu-24.04
              python-version: '3.12'
              toxenv: py312
            - os: ubuntu-24.04
              python-version: '3.13-dev'
              toxenv: py313

    env:
      TOXENV: ${{ matrix.toxenv }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        # just fetching 1 commit is not enough for setuptools-scm, so we fetch all
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python requirements
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements.d/dev.txt
    - name: Install borgstore
      run: pip install -ve .
    - name: run tox env
      run: tox --skip-missing-interpreters
